import{a as b,S as v,i as n}from"./assets/vendor--6n4cVRZ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const f of r.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&c(f)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const B="37881893-de2938aaaa45ff8f8348dc2a6",x="https://pixabay.com/api/";async function y(e,t=1){const s={params:{key:B,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}};return b.get(x,s).then(c=>c.data)}const S=document.querySelector(".gallery"),g=document.getElementById("myButton"),u=document.querySelector(".loader");let R=new v(".gallery a",{captionsData:"alt",captionDelay:250});function L(e){const t=e.map(s=>`
      <li class="gallery-item">
        <a href="${s.largeImageURL}">
          <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" />
        </a>
        <div class="info">
          <p class="info-item-text">Likes <span class="info-item-text-span">${s.likes}</span></p>
          <p class="info-item-text">Views <span class="info-item-text-span">${s.views}</span></p>
          <p class="info-item-text">Comments <span class="info-item-text-span">${s.comments}</span></p>
          <p class="info-item-text">Downloads <span class="info-item-text-span">${s.downloads}</span></p>
        </div>
      </li>
    `).join("");S.insertAdjacentHTML("beforeend",t),R.refresh()}function q(){u&&u.classList.remove("is-hidden")}function p(){u&&u.classList.add("is-hidden")}function E(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function I(){g.style.display="block"}function d(){g.style.display="none"}const P=document.querySelector(".form"),h=document.getElementById("text"),a=document.getElementById("myButton");let i=1,l="";const w=15;function m(e){e?(a.classList.add("loading"),a.disabled=!0):(a.classList.remove("loading"),a.disabled=!1)}function $(){const e=document.querySelector(".gallery li");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}P.addEventListener("submit",M);async function M(e){if(e.preventDefault(),l=h.value.trim(),h.value="",i=1,E(),d(),!l||l===""){n.error({message:"Please enter a search query.",position:"topRight",timeout:3e3});return}try{q();const t=await y(l,i);if(p(),!t.hits||t.hits.length===0){n.error({message:"No images found. Try another query.",position:"topRight",timeout:3e3});return}L(t.hits),i*w>=t.totalHits?(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})):I()}catch(t){p(),n.error({message:"Something went wrong. Try again later.",position:"topRight",timeout:3e3}),console.error(t)}}a.addEventListener("click",async()=>{i+=1,m(!0);try{const e=await y(l,i);if(m(!1),!e.hits||e.hits.length===0){d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3});return}L(e.hits),$(),i*w>=e.totalHits&&(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3}))}catch(e){m(!1),n.error({message:"Something went wrong. Try again later.",position:"topRight",timeout:3e3}),console.error(e)}});
//# sourceMappingURL=index.js.map
